### ISSUE TITLE
Feature Request: Apply Role Mode

### ISSUE THREAD

**Issue by MrSaxon** [Mara-Li/Knitting-bot#1]
Basically a reverse of what the bot does now. instead of looking for someone gaining a role and then adding them to a thread, the bot would give a role to anyone who joins a thread.

At the moment, I have to manually apply roles to people who join threads so that certain other bots don't react to them, so this would be incredibly helpful if possible.

**Comment by Mara-Li** [comment]
Oh, it's an idea, but I think it's outside the scop of the bot :(

**Comment by MrSaxon** [comment]
Ah well. Worth an ask! thanks for the quick response.
